# Production Environment Configuration
base.url=https://crm.example.com/login

browser=chrome
headless.mode=true

implicit.wait=10
explicit.wait=15

sf.username=prod_user@salesforce.com
sf.password=prod_password
sf.security.token=

report.path=test-output/
screenshot.on.failure=true
